name: Delete AIO releases

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  delete-aio-releases:
    runs-on: ubuntu-latest
    steps:
      - name: Check for AIO releases
        run: |
          releases=$(curl -s https://api.github.com/repos/${{ secrets.GITHUB_USERNAME }}/${{ secrets.GITHUB_REPO }}/releases | jq -r '.[] | .name')
          latest_release=$(curl -s https://api.github.com/repos/${{ secrets.GITHUB_USERNAME }}/${{ secrets.GITHUB_REPO }}/releases/latest | jq -r .name)
          for release in $releases; do
            if [[ $release == "AIO-*" ]] && [[ $release != $latest_release ]]; then
              echo "Deleting release $release"
              curl -X DELETE https://api.github.com/repos/${{ secrets.GITHUB_USERNAME }}/${{ secrets.GITHUB_REPO }}/releases/$release
            fi
          done
